Stream lambda fixed
qGamerw/sber-practice_java_test pull request #2
Opened 2022-07-11 09:58 UTC by qGamerw

2022-07-11 18:15 UTC, XLelarX requested changes
папку .idea нужно убрать

2022-07-11 18:15 UTC, XLelarX commented on testjunit/src/test/java/testsjunit/TeamTest.java
> +    public void limitedTeamTest() throws LimitedTeamException {
Тест не проходит, тк вызова переопределенной функции нет

2022-07-11 18:15 UTC, XLelarX commented on testjunit/src/test/java/lambdas/LambdaProgramTest.java
> +                            return a;
LambdaProgram.getNum(() -> 22 / 2)

2022-07-11 18:15 UTC, XLelarX commented on testjunit/src/test/java/lambdas/LambdaProgramTest.java
> +                                return digit + d;
return digit + 10

2022-07-11 18:15 UTC, XLelarX commented on testjunit/src/main/java/streams/StreamFuncs.java
> +        Map<String, String> map = set.stream()
переменная не нужна. можно сразу return сделать
ниже аналогично

2022-07-11 18:15 UTC, XLelarX commented on testjunit/src/main/java/streams/StreamFuncs.java
> +    public static List<String> getListkeyAndValue(HashMap<String, String> map) {
getListkeyAndValue -> getListKeyAndValue (camel case)

2022-07-11 18:15 UTC, XLelarX commented on testjunit/src/test/java/streams/StreamFuncsTest.java
> +        map.put("forth-k", "forth-val");
дублируется мапа. Вынеси в константу

2022-07-11 18:15 UTC, XLelarX commented on testjunit/src/test/java/streams/StreamFuncsTest.java
> +        assertTrue(StreamFuncs.getListKeyEqualValue(map).contains("forth-k == forth-val"));
StreamFuncs.getListKeyEqualValue(map) вынеси в переменную

2022-07-11 18:15 UTC, XLelarX commented on testjunit/src/test/java/streams/StreamFuncsTest.java
> +        assertTrue(StreamFuncs.getListkeyAndValue(map).contains("first-val"));
StreamFuncs.getListkeyAndValue(map) вынеси в переменную

2022-07-11 18:15 UTC, XLelarX commented on testjunit/src/test/java/streams/StreamFuncsTest.java
> +        assertEquals(null, StreamFuncs.getMap(set).get("asd"));
assertEquals -> assertNull

2022-07-11 21:01 UTC, qGamerw commented on testjunit/src/main/java/lambdas/LambdaProgram.java
> +    public static void main(String[] args) {
+

2022-07-11 21:01 UTC, qGamerw commented on testjunit/src/test/java/lambdas/LambdaProgramTest.java
> +                            return a;
+

2022-07-11 21:01 UTC, qGamerw commented on testjunit/src/test/java/lambdas/LambdaProgramTest.java
> +                                return digit + d;
+

2022-07-11 21:01 UTC, qGamerw commented on testjunit/src/main/java/streams/StreamFuncs.java
> +        Map<String, String> map = set.stream()
+

2022-07-11 21:08 UTC, qGamerw commented on testjunit/src/main/java/streams/StreamFuncs.java
> +    public static List<String> getListkeyAndValue(HashMap<String, String> map) {
+

2022-07-12 05:54 UTC, qGamerw commented on testjunit/src/main/java/testsjunit/Team.java
>  @AllArgsConstructor
+

2022-07-12 05:59 UTC, qGamerw commented on testjunit/src/test/java/testsjunit/TeamTest.java
> +    public void limitedTeamTest() throws LimitedTeamException {
+

2022-07-12 06:17 UTC, qGamerw commented on testjunit/src/test/java/testsjunit/TeamTest.java
> +    public void limitedTeamTest() throws LimitedTeamException {
+

2022-07-12 06:17 UTC, qGamerw commented on testjunit/src/test/java/streams/StreamFuncsTest.java
> +        assertEquals(null, StreamFuncs.getMap(set).get("asd"));
+

2022-07-12 06:40 UTC, qGamerw commented on testjunit/src/main/java/testsjunit/Team.java
> +            arrNamesTeam = new ArrayList<String>();
+

2022-07-12 06:40 UTC, qGamerw commented on testjunit/src/test/java/streams/StreamFuncsTest.java
> +        map.put("forth-k", "forth-val");
+

2022-07-12 06:51 UTC, qGamerw commented on testjunit/src/test/java/streams/StreamFuncsTest.java
> +        assertTrue(StreamFuncs.getListKeyEqualValue(map).contains("forth-k == forth-val"));
+

2022-07-12 06:51 UTC, qGamerw commented on testjunit/src/test/java/streams/StreamFuncsTest.java
> +        assertTrue(StreamFuncs.getListkeyAndValue(map).contains("first-val"));
+

2022-07-12 06:51 UTC, qGamerw commented on testjunit/src/main/java/testsjunit/Team.java
> +            arrNamesTeam = new ArrayList<String>();
+

2022-07-12 15:32 UTC, XLelarX commented on testjunit/src/main/java/testsjunit/Team.java
> +            arrNamesTeam = new ArrayList<String>();
Ты что-то не то убрал. ArrayList<String>() -> ArrayList<>()

2022-07-12 15:43 UTC, XLelarX requested changes

2022-07-12 15:43 UTC, XLelarX commented on testjunit/src/main/java/lambdas/LambdaProgram.java
> +import java.util.function.Supplier;
импорты не нужны

2022-07-12 15:43 UTC, XLelarX commented on testjunit/src/main/java/streams/StreamFuncs.java
> +    public static List<String> getListKeyAndValue(HashMap<String, String> map) {
HashMap<String, String> -> Map<String, String>

2022-07-12 15:43 UTC, XLelarX commented on testjunit/src/main/java/streams/StreamFuncs.java
> +    public static List<String> getListKeyEqualValue(HashMap<String, String> map) {
HashMap<String, String> -> Map<String, String>

2022-07-12 15:43 UTC, XLelarX commented on testjunit/src/test/java/streams/StreamFuncsTest.java
> +        listKeyEqualValue = StreamFuncs.getListKeyEqualValue(map);
верни обратно в методы (локальными переменными сделай), а в initializeMap добавь в начале map = new HashMap<>();
listkeyAndValue -> listKeyAndValue

2022-07-12 21:33 UTC, XLelarX requested changes

2022-07-12 21:33 UTC, XLelarX commented on testjunit/src/main/java/streams/StreamFuncs.java
> +    public static List<String> getListKeyAndValue(HashMap<String, String> map) {
Не поменял

2022-07-13 09:53 UTC, merged